### PR TITLE
Market page & Location page

### PR DESCRIPTION
**Pull request by notV4l**
- #64 
- #62

### CODE REVIEW

**Comment by broody** [comment]
Great work! Even game state is hooked up, love it!

We can use higher res panel images left panel eventually, ideally convert to next/image instead of bgImage but I'll create another issue for this

@clicksave any feedback on preview UI? otherwise lgtm!

**Comment by clicksave** [comment]
Yo! Awesome! 

Have a couple comments regarding the ux/ui

---

image

- [ ] Lets remove this component entirely, don't think we need it as the information already exists on the cards themselves. 

---

- [ ] When cards have a 0 balance, the number and bag icon should me muted

image

image

- [ ] Lets also bump up the font size of the balance/cost numbers on the cards. (see new changes in figma) 

---

- [ ] Bag value in the header should be '0/100' instead of '???'

image

---

- [ ] Is it possible to do a custom style for the slider?

image

---

- [ ] Lower bound of the 'buy' & 'sell' page should be '1'

image

---

- [ ] Maximum number of drugs you can have at one time is '100' total, across all drugs. so, for instance, if you have 20 weed, and are buying ludes, you should only be able to purchase '80' even if you can afford more. 

image

---

- [ ] Have an updated illustration for you to use on the buy/sell pages

image

salesman

---

- [ ] Have some higher res versions of the location illustrations as well

Brooklyn
Coney Island
Jersey
Central Park
Bronx
Queens

---

- [ ] Add the day counter

Instead of saying 'Welcome to' it should track what day the player is on 

image

See below 

image

- [ ] Also, looks like theres a discrepancy with the font weight of the title? its a lot heavier in the preview than it is in the mockups

---

The traveling sequence is incorrect. Users will select a location & maybe see a random event before they see the summary page (all of that info needs to be included on the summary page)

https://github.com/cartridge-gg/rollyourown/assets/3332646/b937e75b-b501-4dc3-98ca-3af486821874

---

Thanks for the great work, lmk if any of these asks are unreasonable

**Comment by notV4l** [comment]
> probably not needed here, but i think we need it in the buy/sell screen so maybe keep it here too

**Comment by notV4l** [comment]
> [ ] Lets remove this component entirely, don't think we need it as the information already exists on the cards themselves.

probably not needed here, but i think we need it in the buy/sell screen so maybe keep it here too

**Comment by notV4l** [comment]
> The traveling sequence is incorrect. Users will select a location & maybe see a random event before they see the summary page (all of that info needs to be included on the summary page)

lets create a new issue for this one ? it require a new page / illustrations / change navigation flow

**Comment by clicksave** [comment]
> > The traveling sequence is incorrect. Users will select a location & maybe see a random event before they see the summary page (all of that info needs to be included on the summary page)
> 
> lets create a new issue for this one ? it require a new page / illustrations / change navigation flow

Will do!

**Comment by notV4l** [comment]
> * Lower bound of the 'buy' & 'sell' page should be '1'

keeping 0 is simpler to deal with, quantity selector can't be in an "invalid" state
ie : you can't buy but selector is on 1
or you can't sell but selector is on 1

**Comment by notV4l** [comment]
> 



> The amount of the drug you own is tracked in the bottom right corner and the size of your bag is recorded in the header, so think we can safely omit

i mean on location page, you will then select drug to buy/sell then go back to location and it can happen multiple times
it may look weird if it displays on drug page but not on location page

**Comment by clicksave** [comment]
> 

Gotcha, yeah. I don't think we should display it anywhere, its redundant. Can we do this?

image

image

**Comment by clicksave** [comment]
> > > * Lower bound of the 'buy' & 'sell' page should be '1'
> > 
> > 
> > keeping 0 is simpler to deal with, quantity selector can't be in an "invalid" state ie : you can't buy but selector is on 1 or you can't sell but selector is on 1
> 
> My solution here is to put the 'Buy' or 'Sell' buttons in a disabled state in this scenario. Prefer this to removing the button entirely.
> 
> image

Maybe there should be some conditional help text.. or a color change.  Down to experiment with ways to improve feedback here if people find it confusing. 

image

**Comment by broody** [comment]
@notV4l are you still working on some of these? I don't mind landing these and we can open up new tickets per @clicksave feedbacks

**Comment by notV4l** [comment]
just a few changes left i guess

**Pull request merged**
